version: '3'
services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: nginx
    image: nginx
    volumes:
     - ./code/${APP}/.:/var/www/html
    ports:
     - "8080:80"
    networks:
     - sdnet
    depends_on:
     - php
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: php:7.2
    container_name: php
    volumes:
     - ./code/${APP}/.:/var/www/html
    networks:
     - sdnet
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    image: laravel/node
    volumes:
     - ./code/${APP}/.:/var/www/html
    networks:
     - sdnet
  mysql:
    image: mysql:5.7
    ports:
     - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "my-app"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "passsword"
    volumes:
     - mysqldata:/var/lib/mysql
    networks:
     - sdnet
  redis:
    image: redis:alpine
    container_name: redis
    volumes:
     - redisdata:/data
    networks:
     - sdnet
networks:
  sdnet:
    driver: "bridge"
volumes:
  mysqldata:
    driver: "local"
  redisdata:
    driver: "local"
